version: '3'
services:
  gocd-server:
    image: gocd/gocd-server:v18.6.0
    environment:
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
    ports:
     - 8153:8153
     - 8154:8154
    volumes:
     - ./gocd-server-data:/godata
  gocd-agent-centos:
    build:
      context: .
      dockerfile: Dockerfile.agent-centos
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,java,jre,jdk
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=CentOS JDK Agent
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-default:
    build:
      context: .
      dockerfile: Dockerfile.agent-default
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,deploy
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo,Prod
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu Agent
    depends_on:
     - gocd-server
    restart: always
  # gocd-agent-jdk:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.agent-jdk
  #   environment:
  #    - GO_SERVER_URL=https://gocd-server:8154/go
  #    - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
  #    - AGENT_AUTO_REGISTER_RESOURCES=linux,java,jre,jdk
  #    - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
  #    - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu JDK Agent
  #   depends_on:
  #     - gocd-server
  #   restart: always
  gocd-agent-npm:
    build:
      context: .
      dockerfile: Dockerfile.agent-npm
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,node,npm,nvm
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu NodeJS Agent
    depends_on:
      - gocd-server
    restart: always
  gocd-agent-golang:
    build:
      context: .
      dockerfile: Dockerfile.agent-golang
    environment:
     - GO_SERVER_URL=https://gocd-server:8154/go
     - AGENT_AUTO_REGISTER_KEY=c53fcbb4-0f35-49bc-8186-b3272d15d6ff
     - AGENT_AUTO_REGISTER_RESOURCES=linux,golang,go
     - AGENT_AUTO_REGISTER_ENVIRONMENTS=Build,Demo
     - AGENT_AUTO_REGISTER_HOSTNAME=Ubuntu Golang Agent
    depends_on:
      - gocd-server
    restart: always
  webserver-demo:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    restart: always
    ports:
     - "2222:22"
     - 8000:80
  webserver-prod:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    restart: always
    ports:
     - "2223:22"
     - 9000:80
