FROM gocd/gocd-agent-ubuntu-16.04:v18.2.0

ENV DEBIAN_FRONTEND noninteractive
ENV LANG C.UTF-8

# Install base dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
    apt-transport-https \
    build-essential \
    ca-certificates \
    curl \
    git \
    libssl-dev \
    python \
    rsync \
    software-properties-common \
    wget \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/*

USER go

ENV NVM_VERSION v0.33.8
ENV NODE_VERSION 8.10.0

RUN curl https://raw.githubusercontent.com/creationix/nvm/$NVM_VERSION/install.sh | bash \
    && echo '. ~/.nvm/nvm.sh' >> ~/.bashrc \
    && echo '. ~/.nvm/nvm.sh' >> ~/.profile \
    && . ~/.profile \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

USER root
