FROM gocd/gocd-agent-ubuntu-16.04:v17.12.0

ENV DEBIAN_FRONTEND noninteractive

# Install base dependencies
RUN apt-get update && apt-get install -y -q --no-install-recommends \
    curl \
    wget \
    apt-utils \
    locales \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen fr_FR.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
		golang-go \
	&& rm -rf /var/lib/apt/lists/*
